const request=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
let database;
async function db(){if(database)return database;const r=indexedDB.open('still-local-memories',2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('memories'))r.result.createObjectStore('memories',{keyPath:'id'});if(!r.result.objectStoreNames.contains('drafts'))r.result.createObjectStore('drafts');};database=await request(r);return database;}
export async function save(record){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('memories','readwrite');tx.objectStore('memories').put(record);tx.oncomplete=resolve;tx.onabort=tx.onerror=()=>reject(tx.error||Error('本机存储空间不足'));});}
export async function get(id){return request((await db()).transaction('memories').objectStore('memories').get(id));}
export async function list(){const d=await db();return new Promise((resolve,reject)=>{const rows=[],r=d.transaction('memories').objectStore('memories').openCursor();r.onerror=()=>reject(r.error);r.onsuccess=()=>{const c=r.result;if(!c){resolve(rows.sort((a,b)=>b.created_at.localeCompare(a.created_at)));return;}const {id,name,created_at,ticket,exported_at,photo,model}=c.value;rows.push({id,name,created_at,ticket,exported_at,photo,bytes:(photo?.size||0)+(model?.byteLength||0)});c.continue();};});}
export async function draft(value){const d=await db();if(value===undefined)return request(d.transaction('drafts').objectStore('drafts').get('pending'));return new Promise((resolve,reject)=>{const tx=d.transaction('drafts','readwrite'),store=tx.objectStore('drafts');if(value===null)store.delete('pending');else store.put(value,'pending');tx.oncomplete=resolve;tx.onabort=tx.onerror=()=>reject(tx.error);});}
export function pack(record){const {photo,model,...meta}=record;const json=new TextEncoder().encode(JSON.stringify({...meta,photoType:photo.type,photoBytes:photo.size,modelBytes:model.byteLength}));const head=new Uint32Array([0x4c4c5453,1,json.length]);return new Blob([head,json,photo,model],{type:'application/octet-stream'});}
export async function unpack(file){if(file.size>150*1024*1024)throw Error('记忆文件过大');const data=await file.arrayBuffer(),head=new DataView(data);if(data.byteLength<12||head.getUint32(0,true)!==0x4c4c5453||head.getUint32(4,true)!==1)throw Error('不是有效的 Still 记忆文件');const size=head.getUint32(8,true);if(size>100000||size+12>data.byteLength)throw Error('记忆文件已损坏');const meta=JSON.parse(new TextDecoder().decode(data.slice(12,12+size)));if(!Number.isSafeInteger(meta.photoBytes)||meta.photoBytes<1||!Number.isSafeInteger(meta.modelBytes)||meta.modelBytes<6400||meta.modelBytes%64||12+size+meta.photoBytes+meta.modelBytes!==data.byteLength)throw Error('记忆文件不完整');return {id:crypto.randomUUID(),name:String(meta.name||'一段记忆').slice(0,60),created_at:new Date().toISOString(),settings:meta.settings||{},ticket:normalizeTicket(meta.ticket),photo:new Blob([data.slice(12+size,12+size+meta.photoBytes)],{type:['image/jpeg','image/png','image/webp'].includes(meta.photoType)?meta.photoType:'image/jpeg'}),model:data.slice(12+size+meta.photoBytes)};}

export function normalizeTicket(value){return {city:String(value?.city||'').slice(0,32),venue:String(value?.venue||'').slice(0,60),date:/^\d{4}-\d{2}-\d{2}$/.test(value?.date||'')?value.date:''};}
export async function remove(id){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('memories','readwrite');tx.objectStore('memories').delete(id);tx.oncomplete=resolve;tx.onabort=tx.onerror=()=>reject(tx.error);});}
